version: 2
updates:

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '03:05'
    timezone: JST
  open-pull-requests-limit: 10
  commit-message:
      prefix: "chore"
      include: "scope"
