language: nix

script: |
  cd tests
  ./ci.sh

matrix:
  include:
  - name: emacs-25
    env: NIX_PATH=nixpkgs=channel:nixos-unstable EMACS=emacs25
  - name: nixos-unstable
    env: NIX_PATH=nixpkgs=channel:nixos-unstable
  - name: nixos-18.09
    env: NIX_PATH=nixpkgs=channel:nixos-18.09
  - name: nixos-19.03
    env: NIX_PATH=nixpkgs=channel:nixos-19.03

cache:
  directories:
  - /nix/store
  - /dev/shm/package-lint
