name: 'elinter'
description: 'Lint and test Emacs Lisp packages'
inputs:
  test:
    description: 'How to run tests'
    required: false
    default: ''
  testArgs:
    description: 'Arguments passed to the test runner'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: install elinter
      run: nix-env -if https://github.com/akirak/elinter/archive/v4.tar.gz -A main
      shell: bash
    - name: run elinter
      run: $GITHUB_ACTION_PATH/action.bash
      shell: bash
      env:
        ELINTER_ACTION_TASK: setup
        ELINTER_ACTION_TEST: "${{ inputs.test }}"
        ELINTER_ACTION_TEST_ARGS: "${{ inputs.testArgs }}"
