name: 'elinter'
description: 'Lint Emacs Lisp packages'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/action.bash
      shell: bash
    - name: Check license
      run: |
        nix-shell "$GITHUB_ACTION_PATH/nix/melpazoid-py.nix" -A shell \
        "$GITHUB_ACTION_PATH/license.bash"
      shell: bash
