name: 'elinter'
description: 'Lint and test Emacs Lisp packages'
runs:
  using: 'composite'
  steps:
    - name: Install cachix
      run: 'command -v cachix >/dev/null || nix-env -iA cachix -f https://cachix.org/api/v1/install'
      shell: bash
    - name: Enable nix-emacs-ci
      run: cachix use emacs-ci
      shell: bash
    - name: Install elinter
      run: nix-env -if https://github.com/akirak/elinter/archive/v4.tar.gz -A main
      shell: bash
    - name: Run elinter
      run: elinter -e all --experimental
      shell: bash
