name: 'elinter'
description: 'Lint Emacs Lisp packages'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/action.bash
      shell: bash
    - name: Check license
      shell: bash
      run: |
        for recipe in .recipes/*; do
          LOCAL_REPO="$PWD" nix-shell "$GITHUB_ACTION_PATH/nix/melpazoid-py.nix" \
            -A shell --run "melpazoid --license '$recipe'"
          exit $?
        done
