* elinter
This is a complete rewrite of my Emacs Lisp package checker, formerly called =emacs-package-checker= or =melpa-check=. It is currently at an early alpha stage, and most of its planned features are not implemented yet.
** Planned features [38%]
The following is a list of features that should be supported by this project.
Maybe I'll announce this project officially when the progress reaches around 80%.

Linting (extracted from [[https://github.com/alphapapa/makem.sh][makem.sh]] + inspiration from [[https://github.com/gonewest818/elisp-lint][elisp-lint]]):

- [X] checkdoc
- [X] package-lint
- [X] check-declare
- [X] melpazoid (sharp quotes and other experimental checks)
- [ ] ELSA
- [ ] indentation
- [ ] regular expressions
- [ ] whitespace

Building packages:

- [X] Byte-compile
- [X] Loadability testing
- [X] Produce a package with =*-autoloads.el= file

Testing:

- [ ] buttercup
- [ ] ert-runner
- [ ] Start Emacs with any arguments

Configuration:

- [X] Allow specifying an Emacs version available in =nix-emacs-ci=
- [X] Determining Emacs versions based on the package header
- [ ] Activate extra packages listed in =Cask= file
- [ ] Let the user define custom package derivations
- [ ] Allow updating emacs-overlay independently from the upstream
- [ ] Switch to flakes

Integration:

- [X] CLI for local use
- [ ] Git pre-commit hook (run static checks only on modified files)
- [ ] GitHub Actions

Reporting:

- [ ] Colorizing statuses
- [ ] Produce structured output for GitHub Actions
** Prerequisites
=elinter= runs on UNIX-like operating systems that can run [[https://nixos.org/][Nix]] (currently Linux and macOS).
** Installation
=elinter= depends on Nix, so you have to install Nix first:

#+begin_src sh
bash <(curl -L https://nixos.org/nix/install)
#+end_src

=elinter= can be installed using Nix:

#+begin_src sh
nix-env -if https://github.com/akirak/elinter/archive/v4.tar.gz -A main
#+end_src

Alternatively, you can clone this repository and run

#+begin_src sh
nix-env -iA main
#+end_src

Optionally, it is recommended to install [[https://github.com/cachix/cachix][cachix]] and enable cached binaries:

#+begin_src sh
cachix use emacs-ci
#+end_src

Optionally, you can use [[https://github.com/xzfc/cached-nix-shell][cached-nix-shell]] for improving =nix-shell= startup time.
Install the program in =PATH=, and =elinter= will automatically detect it.
** Usage
*** Use case #1: Local source + in-repository recipes
First create package recipes in =.recipes= directory.
You can use [[https://github.com/akirak/decask.el][decask.el]] to copy existing recipes from a local copy of MELPA.

Then run the following command to lint and compile source files in the repository:

#+begin_src sh
elinter
#+end_src

To perform extra checks from [[https://github.com/riscy/melpazoid/][melpazoid]] as done in PR reviews on MELPA, add =--melpazoid= flag:

#+begin_src sh
elinter --melpazoid
#+end_src

To only lint packages and prevent from byte-compiling, add =-l= flag:

#+begin_src sh
elinter -l
#+end_src

To only byte-compile source files, add =-b= flag:

#+begin_src sh
elinter -b
#+end_src
*** Use case #2: Local recipes + remote sources
This is like the use case 1, but it clones the remote repository specified in the recipe rather than work on source files in the working directory.

=elinter= command accepts recipe files. When =-r= flag is given, it clones remote Git repositories according to the recipes.
This can be easily integrated into the MELPA PR workflow:

#+begin_src sh
cd ~/your-melpa-fork
elinter -r recipes/your-package
#+end_src
** Technical details
*** elinter command
The =main= Nix derivation provides =elinter= executable.
It takes recipe files as command-line arguments.
If no recipe file is given as an argument, it looks for ones in =.recipes= directory in the working directory.
** Credits, inspiration sources, and alternatives
=elinter= is influenced by or using code from the following projects:

- [[https://github.com/nix-community/emacs-overlay/][emacs-overlay]] from the Nix community, its =emacsWithPackagesFromPackageRequires= parser by Steve Purcell, and [[https://github.com/talyz/fromElisp][fromElisp]] parser by Kim Lindberger (used in [[https://github.com/akirak/nix-elisp-helpers][my Nix library]]).
- [[https://github.com/alphapapa/makem.sh][makem.sh]] by Adam Porter (alphapapa), for some of its linting code and the idea of extensive use of bash
- [[https://github.com/riscy/melpazoid/][melpazoid]] by Chris Rayner (riscy), for extra linting features and the idea of sandboxing
- [[https://github.com/conao3/keg.el/][keg.el]] by Naoya Yamashita (conao3), for its recipe-oriented configuration API
- [[https://github.com/DamienCassou/nix-hello-world][nix-hello-world]] by Damien Cassou, for configuring Nix projects
- [[https://gitea.petton.fr/DamienCassou/makel][makel]] by Damien Cassou, for some linting code

=elinter= is an improvement upon the previous version, which was helped by [[https://github.com/ericdallo][Eric Dallo]] and [[https://github.com/terlar][Terje Larsen]].
