name: 'Action CI'
on:
  push:
    paths-ignore:
      - '*.org'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v10
    - uses: actions/checkout@v2
    - uses: ./
