name: 'GitHub Action'
on:
  pull_request:
  push:
    paths-ignore:
    - '**.org'
    branches:
    - v4
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs_channel:
        - nixos-21.05-small
        - nixos-unstable-small
    steps:
    - uses: cachix/install-nix-action@v14
      with:
        nix_path: nixpkgs=channel:${{ matrix.nixpkgs_channel }}
    - uses: actions/checkout@v2.3.4
    - uses: ./
    - run: elinter -t --buttercup -e latest
    - run: elinter -t --buttercup -e snapshot
