name: 'GitHub Action'
on:
  pull_request:
    branches-ignore:
    - pr/update-deps-v4
  push:
    branches:
    - v4
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs_channel:
        - nixos-unstable-small
    steps:
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:${{ matrix.nixpkgs_channel }}
    - uses: actions/checkout@v3
    - uses: ./
    - run: elinter -t --buttercup -e latest
    - run: elinter -t --buttercup -e snapshot
