name: "CLI"

on:
  push:
    # branches:
    # - v3
    paths-ignore:
    - 'README.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v8
    - uses: actions/checkout@v2
    - name: Install
      run: nix-env -iA cli.gh-action -f .
    - run: command -v melpa-check
    - run: melpa-check --version
    - run: melpa-check deps
    - run: melpa-check config -f tests
    - run: melpa-check lint hello
    - run: melpa-check byte-compile -e 26.2
    - run: melpa-check buttercup -e 26.3 hello
    - run: melpa-check buttercup -e snapshot hello
    - run: cd cli; nix-shell --command "make -f build.mk"
    - name: Check if the HEAD version is up-to-date
      run: git diff-tree HEAD -- cli/dist.js
