name: 'Demo'
on:
  push:
    paths-ignore:
      - '*.org'
      - '*.el'
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    # Install Nix
    - uses: cachix/install-nix-action@v10
    - name: Set up binary cache
      run: nix-env -iA cachix -f https://cachix.org/api/v1/install && cachix use emacs-ci

    # Install and configure elinter
    - uses: actions/checkout@v2
      with:
        path: elinter
    - name: Install elinter
      working-directory: ./elinter
      run: nix-env -if . -A main
    - name: Set linters
      run: echo "::set-env name=ELINTER_LINTERS::checkdoc check-declare package-lint melpazoid"

    # Demo

    - name: Check out lsp-dart
      uses: actions/checkout@v2
      with:
        repository: akirak/lsp-dart
        ref: elinter
        path: lsp-dart
    - run: elinter --ert-runner
      working-directory: ./lsp-dart
      env:
        ELINTER_ALLOW_WARNINGS: melpazoid
