name: "elisp-ci"

on:
  push:
    # branches:
    # - v3
    paths:
    - 'nix/checkers/*.el'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs:
          - 25.1
          - 26.1
          - 26.2
          - 26.3
          - snapshot
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v8
    - uses: actions/checkout@v2
    - name: Install
      run: nix-env -iA cli.gh-action -f .
    - run: melpa-check deps
    - run: melpa-check config -f nix/checkers/tests
    # Continue even if there is an error
    - run: melpa-check lint checkdoc-runner || echo Ignoring
    - run: melpa-check byte-compile -e ${{ matrix.emacs }} checkdoc-runner
    - run: melpa-check lint package-lint-runner || echo Ignoring
    - run: melpa-check byte-compile -e ${{ matrix.emacs }} package-lint-runner
