name: 'Tests'
on:
  pull_request:
  push:
    paths-ignore:
    - '**.org'
    branches:
    - v4
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs_channel:
        - nixos-20.03-small
        - nixos-20.09-small
        - nixos-unstable-small
    steps:
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:${{ matrix.nixpkgs_channel }}
    - name: Set up cachix
      run: |
        nix-env -iA cachix -f https://cachix.org/api/v1/install
        cachix use emacs-ci
    - uses: actions/checkout@v2
    - run: nix-shell test/shell.nix
