name: Update dependencies
on:
  schedule:
    # Run the job twice a month
    - cron:  '0 5 9,24 * *'
jobs:
  niv-updater:
    name: 'Create PRs for niv-managed dependencies'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
